apiVersion: v2
name: komga
description: Komga comics and manga server. Wrapper around the true-kube Komga library chart.
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.22.0-0"
keywords:
  - komga
  - comics
  - manga
  - media
home: https://komga.org
sources:
  - https://github.com/gotson/komga
dependencies:
  - name: komga
    version: 0.1.7
    repository: https://gitlab.com/api/v4/projects/43892189/packages/helm/stable
